:sectnums:

= A very simple game

== Introduction

A very trivial video game with a textual interface, where several "pawns" have to fight by moving on the squares of a board. Written in Java.

== Rules of the game

* The setting is a rectangular board, divided in X × Y squares, with two random "bonus" squares, and with N pawns distributed randomly over the board.
* Each pawn has a letter (A, B, C, etc.), and turns are based on the order of the letters (e.g. A plays first, then B plays, then C plays, etc.)
* At each turn, a pawn acts in a direction (up, down, left, right):
** If the square is empty, it moves there.
** If it encounters a pawn, it attacks the pawn and hurts it.
** If it tries to act out of the board, it loses its turn.
* When attacking, a pawn normally inflicts 1 damage to another pawn. 
However, it inflicts twice the amount if it is on a "bonus" square. 
If a pawn kills another one, it earns 1 gold.
* A pawn has 6 hitpoints
* The game is over either when there is 1 pawn left, either when a pawn has 3 golds.


== Informations for developers

=== Compiling and running the game for development

Builds are managed using _maven_. 
To compile simply run:

....
mvn compile
....

Then to run the game:

....
mvn exec:java
....

The game then starts, and shows you a board with both Pawns and the bonus squares. 
A Pawn is either shown as a single letter (`A` or `B`), and is colored in blue (or green when the Pawn is on a bonus square) when it is its turn. 
A bonus square is shown as a yellow `#`.

You can type a number between 0 and 3 on your keyboard to select the direction you want the current pawn to pick, and then validate this choice with your return key.

=== Packaging and distribution the game

To produce a single executable jar file with all dependencies, simply run:

....
mvn package
....

This will produce a file `target/simpleGame-1-jar-with-dependencies.jar` which can be easily distributed, and used with a simple `java` command:

....
java -jar simpleGame-1-jar-with-dependencies.jar
....


=== Organisation of the code

* `simplegame.cli`: Package with the user interface and the main method.
** `CLIMain`: The main class, to play the game with a console interface.
* `simplegame.core`: Package with the main classes.
** `Board Class`: that describes the board.
** `Direction`: Enumeration of the directions a Pawn can follow.
** `Game`: Class to initialize and interact with the game.
** `Pawn`: Class that describes the state and behavior of a Pawn.
** `Position`: Class that describes a (x,y) position.
* `simplegame.exception`: Package with the exceptions used.
** `ImpossibleActionException`: Sent when a Pawn cannot perform an action.
* `simplegame.uil`: Package with some utiliy classes.
** `CharUtil`: Class with operations to manipulate chars.
** `Logger`: Class to print messages.
** `StringColoring`: Class to make colored String that can be printed in a console.